import type { Locale } from "@/src/lib/i18n";

/** Testi delle pagine camere (lista e dettaglio) in IT / EN / DE. */
export const roomsCopy = {
  it: {
    breadcrumbLabel: "Percorso",
    home: "Home",
    rooms: "Camere",
    listH1: "Camere a Isola di Capo Rizzuto",
    listIntro:
      "Quattro camere matrimoniali indipendenti, ognuna con bagno privato, aria condizionata e colazione inclusa. Ospitiamo fino a 8 persone: per famiglie o gruppi si possono prenotare più camere.",
    from: "da",
    perNight: "a notte",
    details: "Dettagli camera",
    guests: (n: number) => `${n} ospiti`,
    doubleRoom: (m2: number) => `Camera matrimoniale · ${m2} m² · bagno privato`,
    metaTitle: (name: string, m2: number) => `${name}, matrimoniale ${m2} m² | Residence Le Farfalle`,
    ctaTitle: "Hai già le date?",
    ctaText: "Scrivici date e numero di ospiti: ti rispondiamo con disponibilità e prezzo esatto, senza impegno.",
    cta: "Richiedi disponibilità",
    gallery: "Foto",
    amenities: "In camera",
    otherRooms: "Le altre camere",
    breakfastIncluded: "Colazione inclusa",
    requestThisRoom: "Richiedi disponibilità per questa camera",
    requestNote: "Non è una prenotazione immediata: ti confermiamo disponibilità e prezzo via email o WhatsApp.",
    galleryLabels: {
      open: "Apri foto {n}",
      close: "Chiudi",
      prev: "Foto precedente",
      next: "Foto successiva",
      dialog: "Galleria foto",
    },
    locationNote: "Nel centro di Isola di Capo Rizzuto. Spiagge dell’Area Marina Protetta a circa 6 km, 10–15 minuti in auto.",
    notFound: "Camera non trovata",
  },
  en: {
    breadcrumbLabel: "Breadcrumb",
    home: "Home",
    rooms: "Rooms",
    listH1: "Rooms in Isola di Capo Rizzuto",
    listIntro:
      "Four independent double rooms, each with private bathroom, air conditioning and breakfast included. We host up to 8 guests: families and groups can book more than one room.",
    from: "from",
    perNight: "per night",
    details: "Room details",
    guests: (n: number) => `${n} guests`,
    doubleRoom: (m2: number) => `Double room · ${m2} m² · private bathroom`,
    metaTitle: (name: string, m2: number) => `${name}, double room ${m2} m² | Residence Le Farfalle`,
    ctaTitle: "Got your dates?",
    ctaText: "Send us your dates and number of guests: we'll reply with availability and the exact price, no obligation.",
    cta: "Check availability",
    gallery: "Photos",
    amenities: "In the room",
    otherRooms: "Other rooms",
    breakfastIncluded: "Breakfast included",
    requestThisRoom: "Check availability for this room",
    requestNote: "This is not an instant booking: we confirm availability and price by email or WhatsApp.",
    galleryLabels: {
      open: "Open photo {n}",
      close: "Close",
      prev: "Previous photo",
      next: "Next photo",
      dialog: "Photo gallery",
    },
    locationNote: "In the centre of Isola di Capo Rizzuto. Marine Protected Area beaches about 6 km away, 10–15 minutes by car.",
    notFound: "Room not found",
  },
  de: {
    breadcrumbLabel: "Brotkrumennavigation",
    home: "Startseite",
    rooms: "Zimmer",
    listH1: "Zimmer in Isola di Capo Rizzuto",
    listIntro:
      "Vier unabhängige Doppelzimmer, jeweils mit eigenem Bad, Klimaanlage und Frühstück inklusive. Wir beherbergen bis zu 8 Gäste: Familien und Gruppen können mehrere Zimmer buchen.",
    from: "ab",
    perNight: "pro Nacht",
    details: "Zimmerdetails",
    guests: (n: number) => `${n} Gäste`,
    doubleRoom: (m2: number) => `Doppelzimmer · ${m2} m² · eigenes Bad`,
    metaTitle: (name: string, m2: number) => `${name}, Doppelzimmer ${m2} m² | Residence Le Farfalle`,
    ctaTitle: "Stehen Ihre Reisedaten fest?",
    ctaText: "Nennen Sie uns Reisedaten und Gästezahl: Wir antworten mit Verfügbarkeit und genauem Preis, unverbindlich.",
    cta: "Verfügbarkeit anfragen",
    gallery: "Fotos",
    amenities: "Im Zimmer",
    otherRooms: "Weitere Zimmer",
    breakfastIncluded: "Frühstück inklusive",
    requestThisRoom: "Verfügbarkeit für dieses Zimmer anfragen",
    requestNote: "Keine Sofortbuchung: Verfügbarkeit und Preis bestätigen wir per E-Mail oder WhatsApp.",
    galleryLabels: {
      open: "Foto {n} öffnen",
      close: "Schließen",
      prev: "Vorheriges Foto",
      next: "Nächstes Foto",
      dialog: "Fotogalerie",
    },
    locationNote: "Im Zentrum von Isola di Capo Rizzuto. Strände des Meeresschutzgebiets ca. 6 km entfernt, 10–15 Autominuten.",
    notFound: "Zimmer nicht gefunden",
  },
} as const satisfies Record<Locale, unknown>;
