/**
 * Testi dell'interfaccia condivisa (header, footer, banner, CTA comuni).
 * Unica fonte per IT / EN / DE: evita stringhe italiane nelle pagine tradotte.
 */
import type { Locale } from "@/src/lib/i18n";

export const uiCopy = {
  it: {
    skipToContent: "Vai al contenuto",
    mainNav: "Navigazione principale",
    ctaAvailability: "Richiedi disponibilità",
    ctaAvailabilityShort: "Disponibilità",
    openMenu: "Apri menu",
    closeMenu: "Chiudi menu",
    menu: "Menu",
    changeLanguage: "Cambia lingua",
    homeLink: "Residence Le Farfalle, pagina iniziale",
    footerLinks: "Link rapidi",
    footerRooms: "Le camere",
    footerContacts: "Contatti",
    footerTagline:
      "Quattro camere matrimoniali con bagno privato e colazione inclusa nel centro di Isola di Capo Rizzuto. Le spiagge dell'Area Marina Protetta sono a circa 6 km, 10–15 minuti in auto.",
    privacy: "Informativa privacy",
    cookie: "Cookie policy",
    terms: "Termini e condizioni",
    vatOnRequest: "P.IVA/C.F. disponibile su richiesta",
    whatsappPrefill: "Ciao! Vorrei informazioni su Residence Le Farfalle",
    whatsappLabel: "Scrivici su WhatsApp",
    whatsappShort: "Scrivici",
    bandieraRegion: "Annuncio Bandiera Blu 2026",
    cookieTitle: "Cookie e privacy",
    cookieText:
      "Usiamo solo cookie tecnici, più Google Analytics se lo accetti. Puoi cambiare idea in qualsiasi momento.",
    cookieAcceptAll: "Accetta analytics",
    cookieNecessary: "Solo necessari",
    cookiePrefs: "Preferenze",
    cookiePrefsTitle: "Preferenze cookie",
    cookieNecessaryAlways: "Necessari (sempre attivi)",
    cookieAnalytics: "Statistiche (Google Analytics)",
    cookieMarketing: "Marketing",
    cookieSave: "Salva preferenze",
    cookieManage: "Preferenze cookie",
  },
  en: {
    skipToContent: "Skip to content",
    mainNav: "Main navigation",
    ctaAvailability: "Check availability",
    ctaAvailabilityShort: "Availability",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    menu: "Menu",
    changeLanguage: "Change language",
    homeLink: "Residence Le Farfalle, home page",
    footerLinks: "Quick links",
    footerRooms: "Rooms",
    footerContacts: "Contact",
    footerTagline:
      "Four double rooms with private bathroom and breakfast included in the centre of Isola di Capo Rizzuto. The beaches of the Marine Protected Area are about 6 km away, 10–15 minutes by car.",
    privacy: "Privacy policy",
    cookie: "Cookie policy",
    terms: "Terms and conditions",
    vatOnRequest: "VAT/tax code available on request",
    whatsappPrefill: "Hello! I'd like some information about Residence Le Farfalle",
    whatsappLabel: "Message us on WhatsApp",
    whatsappShort: "Message us",
    bandieraRegion: "Blue Flag 2026 announcement",
    cookieTitle: "Cookies and privacy",
    cookieText:
      "We only use technical cookies, plus Google Analytics if you accept it. You can change your mind at any time.",
    cookieAcceptAll: "Accept analytics",
    cookieNecessary: "Necessary only",
    cookiePrefs: "Preferences",
    cookiePrefsTitle: "Cookie preferences",
    cookieNecessaryAlways: "Necessary (always on)",
    cookieAnalytics: "Statistics (Google Analytics)",
    cookieMarketing: "Marketing",
    cookieSave: "Save preferences",
    cookieManage: "Cookie preferences",
  },
  de: {
    skipToContent: "Zum Inhalt springen",
    mainNav: "Hauptnavigation",
    ctaAvailability: "Verfügbarkeit anfragen",
    ctaAvailabilityShort: "Verfügbarkeit",
    openMenu: "Menü öffnen",
    closeMenu: "Menü schließen",
    menu: "Menü",
    changeLanguage: "Sprache ändern",
    homeLink: "Residence Le Farfalle, Startseite",
    footerLinks: "Schnellzugriff",
    footerRooms: "Zimmer",
    footerContacts: "Kontakt",
    footerTagline:
      "Vier Doppelzimmer mit eigenem Bad und Frühstück im Zentrum von Isola di Capo Rizzuto. Die Strände des Meeresschutzgebiets liegen ca. 6 km entfernt, 10–15 Minuten mit dem Auto.",
    privacy: "Datenschutz",
    cookie: "Cookie-Richtlinie",
    terms: "AGB",
    vatOnRequest: "USt-IdNr./Steuernummer auf Anfrage",
    whatsappPrefill: "Hallo! Ich hätte gern Informationen zum Residence Le Farfalle",
    whatsappLabel: "Schreiben Sie uns auf WhatsApp",
    whatsappShort: "Schreiben",
    bandieraRegion: "Hinweis Blaue Flagge 2026",
    cookieTitle: "Cookies und Datenschutz",
    cookieText:
      "Wir verwenden nur technische Cookies und – mit Ihrer Zustimmung – Google Analytics. Sie können Ihre Wahl jederzeit ändern.",
    cookieAcceptAll: "Analytics akzeptieren",
    cookieNecessary: "Nur notwendige",
    cookiePrefs: "Einstellungen",
    cookiePrefsTitle: "Cookie-Einstellungen",
    cookieNecessaryAlways: "Notwendig (immer aktiv)",
    cookieAnalytics: "Statistik (Google Analytics)",
    cookieMarketing: "Marketing",
    cookieSave: "Einstellungen speichern",
    cookieManage: "Cookie-Einstellungen",
  },
} as const satisfies Record<Locale, Record<string, string>>;

export type UiCopy = (typeof uiCopy)[Locale];
